# SERVICIO-CATALOGO

spring:
  application:
    name: SERVICIO-CATALOGO

  datasource:
    # url: jdbc:postgresql://localhost:26259/catalogo_db
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  rabbitmq:
    # host: localhost
    host: ${RABBITMQ_HOST:rabbitmq-svc}
    # port: 5672
    port: ${RABBITMQ_PORT:5672}
    # username: admin
    username: ${RABBITMQ_USERNAME:admin}
    # password: admin
    password: ${RABBITMQ_PASSWORD:admin}

eureka:
  client:
    # service-url:
    #   defaultZone: http://localhost:8761/eureka/
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://eureka-server-svc:8761/eureka/}
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.value}

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway

# server:
#   port: 0
server:
  port: ${PORT:7002}

logging.level.org.springframework.security: DEBUG
