# API-GATEWAY

# server:
#   port: 8000
server:
  port: ${PORT:8000} # API Gateway sí se queda en 8000
  address: 0.0.0.0

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: publicaciones-autor
          uri: lb://SERVICIO-PUBLICACIONES
          predicates:
            - Path=/api/autores/**
          filters:
            - StripPrefix=1
        - id: publicaciones-libros
          uri: lb://SERVICIO-PUBLICACIONES
          predicates:
            - Path=/api/libros/**
          filters:
            - StripPrefix=1
        - id: publicaciones-papers
          uri: lb://SERVICIO-PUBLICACIONES
          predicates:
            - Path=/api/papers/**
          filters:
            - StripPrefix=1
        - id: notificaciones
          uri: lb://SERVICIO-NOTIFICACIONES
          predicates:
            - Path=/api/notificaciones
          filters:
            - StripPrefix=1
        - id: catalogo
          uri: lb://SERVICIO-CATALOGO
          predicates:
            - Path=/api/catalogo
          filters:
            - StripPrefix=1
        - id: auth-login
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=1
        - id: roles
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/roles/**
          filters:
            - StripPrefix=1
        # ESPECIAL: sin StripPrefix para Swagger
        - id: auth-swagger
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/swagger/auth/v3/api-docs
          filters:
            - StripPrefix=2
        - id: prublicaciones-swagger
          uri: lb://SERVICIO-PUBLICACIONES
          predicates:
            - Path=/swagger/publicaciones/v3/api-docs
          filters:
            - StripPrefix=2
        - id: notificaciones-swagger
          uri: lb://SERVICIO-NOTIFICACIONES
          predicates:
            - Path=/swagger/notificaciones/v3/api-docs
          filters:
            - StripPrefix=2
        - id: catalogo-swagger
          uri: lb://SERVICIO-CATALOGO
          predicates:
            - Path=/swagger/catalogo/v3/api-docs
          filters:
            - StripPrefix=2
        - id: sincronizacion
          uri: lb://SERVICIO-SINCRONIZACION
          predicates:
            - Path=sinc/**

  # spring.eureka.client.service-url.defaultZone: http://localhost:8761/eureka/
  eureka:
    client:
      service-url:
        defaultZone: ${EUREKA_SERVER_URL:http://eureka-server-svc:8761/eureka/}
      fetch-registry: true
      register-with-eureka: true
    instance:
      prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway


logging:
  level:
    com.netflix.discovery: DEBUG
