apiVersion: v1
kind: Service
metadata:
  name: authservice-svc
spec:
  selector:
    app: authservice
  ports:
    - protocol: TCP
      port: 7001       # Puerto expuesto en el cluster
      targetPort: 7001 # Puerto en el contenedor
  type: ClusterIP
