apiVersion: apps/v1
kind: Deployment
metadata:
  name: cockroachdb-node4
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cockroachdb-node4
  template:
    metadata:
      labels:
        app: cockroachdb-node4
    spec:
      containers:
        - name: cockroachdb
          image: cockroachdb/cockroach:latest
          command: ["/bin/sh", "-c"]
          args:
            - exec cockroach start --insecure --store=node4 --listen-addr=0.0.0.0:26257 --http-addr=0.0.0.0:8080 --join=cockroachdb-svc --advertise-addr=$POD_IP
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          ports:
            - containerPort: 26257
            - containerPort: 8080
          volumeMounts:
            - name: cockroach-data
              mountPath: /cockroach/cockroach-data
      volumes:
        - name: cockroach-data
          emptyDir: {}
