apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-notificaciones-deploy
  labels:
    app: ms-notificaciones
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-notificaciones
  template:
    metadata:
      labels:
        app: ms-notificaciones
    spec:
      containers:
        - name: ms-notificaciones
          image: zuix1384/ms-notificaciones:latest
          ports:
            - containerPort: 7003
          env:
            - name: DB_URL
              value: jdbc:postgresql://cockroachdb-node4:26257/notificaciones_db?sslmode=disable
            - name: DB_USERNAME
              value: root
            - name: DB_PASSWORD
              value: ""
            - name: RABBITMQ_HOST
              value: rabbitmq-svc
            - name: RABBITMQ_PORT
              value: "5672"
            - name: RABBITMQ_USERNAME
              value: admin
            - name: RABBITMQ_PASSWORD
              value: admin
            - name: EUREKA_SERVER_URL
              value: http://eureka-server-svc:8761/eureka/
            - name: PORT
              value: "7003"
