apiVersion: v1
kind: Service
metadata:
  name: ms-notificaciones-svc
spec:
  selector:
    app: ms-notificaciones
  ports:
    - protocol: TCP
      port: 7003
      targetPort: 7003
  type: ClusterIP
