apiVersion: v1
kind: Service
metadata:
  name: ms-sincronizacion-svc
spec:
  selector:
    app: ms-sincronizacion
  ports:
    - protocol: TCP
      port: 7005
      targetPort: 7005
  type: ClusterIP
